"""removes likes from Post

Revision ID: 23329f57ccbe
Revises: b5beeffd4640
Create Date: 2023-09-29 08:15:15.563343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23329f57ccbe'
down_revision = 'b5beeffd4640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
